### PR TITLE
Add istio-operator 2.1 jobs

### PR DESCRIPTION
**Pull request by jwendell**
And remove an unsed `release` job.

### CODE REVIEW

**Review by dgn — COMMENTED** [review]
I think adding the branch to the existing job would be sufficient

**Comment by jwendell** [comment]
Yeah, but the existent job runs 1.1 and 2.0 tests. We should bump the image to 2.1, and guarantee backward compatibility. Do we want to do that?

**Comment by dgn** [comment]
> Yeah, but the existent job runs 1.1 and 2.0 tests. We should bump the image to 2.1, and guarantee backward compatibility. Do we want to do that?

Bumping the image is not really required; we haven't changed anything about `maistra/istio-operator` that would require a new version of anything. The new image is only really required for `maistra/istio`- I don't even know if it can run the operator unit tests, haven't tested it.

I guess it doesn't hurt to use the new image. Could you verify locally that it works? Then I'm fine with merging this as-is

**Comment by jwendell** [comment]
Yes, it works locally.

Anyway, I'd go beyond "it doesn't hurt to use the new image" in the sense that it's about consistency rather than "it's technically possible to use an old image". If something fails on 2.1 branch, we should fix it in 2.1 images, it should be straightforward.

**Review by dgn — APPROVED** [review]

**Pull request merged**
