### PR TITLE
Disable unnecessary multicluster tests

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jewertow@redhat.com>

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
Do you want to create a Jira issue to reenable them at some point?

**Comment by jewertow** [comment]
I think we can enable them once we are ready for multi-cluster support.

**Comment by luksa** [comment]
@jewertow How come you didn't remove all the -mc tests? I can still see some.

**Comment by jwendell** [comment]
only left is servicemesh-mc

**Comment by jewertow** [comment]
@luksa I left only `istio-integration-servicemesh-2.3-mc` which runs federation test.

**Pull request merged**
