### PR TITLE
Install acorn module in /opt/emsdk (OSSM-1931)

### PR DESCRIPTION
**Pull request by dcillera**
This is one of the necessary modifications to build Proxy with WASM enabled and without downloading any modules from the internet.

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]

**Review by jwendell — CHANGES_REQUESTED** [review]
I think this is not the right approach. This is a dependency and should be somehow vendored in the source code.

We will need it in brew too, so, installing this in the container image is not the right solution.

**Comment by jwendell** [comment]
Another solution other than vendoring it in the source code is creating a RPM for the acorn package, that installs it on the system, in the same way we did with emsdk. Then we can install this RPM both in our builder image and have it as a dependency on brew (like what we have for emsdk, bazel, etc)

**Comment by dcillera** [comment]
Does this mean that we  should create a Red Hat's acorn package as in the case of emscripten?

**Comment by jwendell** [comment]
Yes, or somehow vendor this package into our maistra/vendor directory. Perhaps vendoring it is easier and faster, as we wouldn't require another build time dependency (rpm) in our brew build root.

**Comment by dcillera** [comment]
Closed, because a different approach will be used

**Pull request closed without merging**
