### PR TITLE
Bump golangci-lint to v1.44.2

### PR DESCRIPTION
**Pull request by luksa**
v1.44.0 doesn't install due to a bad checksum in a dependency

### CODE REVIEW

**Comment by jwendell** [comment]
What do you mean by `doesn't install`?

```
$ docker run --rm -it --entrypoint golangci-lint quay.io/maistra-dev/maistra-builder:2.3 --version
golangci-lint has version v1.44.0 built from (unknown, mod sum: "h1:YJPouGNQEdK+x2KsCpWMIBy0q6MSuxHjkWMxJMNj/DU=") on (unknown)
```

**Comment by luksa** [comment]
```
$ go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.0
go: downloading github.com/golangci/golangci-lint v1.44.0
go: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.0: github.com/golangci/golangci-lint@v1.44.0 requires
        github.com/mgechev/revive@v1.1.3: verifying go.mod: checksum mismatch
        downloaded: h1:ZZq2bmyssGh8MSPz3VVziqRNIMYTJXzP8MUKG90vZ9A=
        sum.golang.org: h1:jMzDa13teAuv/KLeqgJw79NDe+1IT0ZO3Mht0vN1Yls=
```
This is what happens on a clean machine with no go mod cache. Not sure how the image build succeeded.

**Comment by luksa** [comment]
Also: https://github.com/golangci/golangci-lint/issues/2575

**Comment by jwendell** [comment]
weird, that works for me:
```
 docker run --rm -it --entrypoint go golang:1.18 install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.0
```

**Comment by jwendell** [comment]
@luksa should we close this one?

**Comment by luksa** [comment]
Yup.

**Pull request closed without merging**
