### PR TITLE
Remove jobs unit, lint and gen-check for Istio 2.3

### PR DESCRIPTION
**Pull request by jewertow**

### CODE REVIEW

**Comment by jwendell** [comment]
@jewertow do you know why lint is failing on openshift ci but succeeding on our prow, or even locally?

**Comment by jewertow** [comment]
I'm looking at this problem. gen-check on the other hand fails, because `buf` command does not exist. I'm checking our builder images locally and will try to fix it.

**Comment by jwendell** [comment]
@jewertow I think this is the problem: https://github.com/openshift/release/pull/32678
cc @yxun

**Comment by jwendell** [comment]
@yxun That's not the issue. I just picked the latest image from 1.14 branch.

**Review by jwendell — APPROVED** [review]
I believe this is ready to go in.

Jobs proved to be stable (https://github.com/maistra/istio/pull/638 , https://github.com/maistra/istio/pull/637)

**Pull request merged**
