### PR TITLE
feat(prow): adds merge conflict workflow

### PR DESCRIPTION
**Pull request by bartoszmajsak**
This PR brings conflict detection workflow.

Related repos:
  * jobs: https://github.com/bartoszmajsak/repo-sync/
  * custom plugin: https://github.com/bartoszmajsak/prow-patch-propagator

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@dgn we could automate `make gen` in a job and push it back instead of failing and round-tripping to the poor developer opening a PR :)

**Comment by dgn** [comment]
> @dgn we could automate `make gen` in a job and push it back instead of failing and round-tripping to the poor developer opening a PR :) If that's of interest I can make this happen in separate PR.

heh. sounds cool. separate PR would be good, though!

**Comment by bartoszmajsak** [comment]
@yxun it's not about detecting merge conflicts between what's in the PR and the target branch, but what are the conflicts between maistra-specific commits applied on top of upstream `main` branch to see where we have issues. You can think of it as an interactive rebase through GitHub PR. It takes care of storing those changes in the external repository as a patchset. This lets us apply them every time there's a new change in the upstream branch so we don't have to do a big shabang rebase next time.

The plugin is a small part of the whole workflow and it does handle jobs annotated with a special label on a default branch name change.

**Pull request closed without merging**
